# BioGPT
Microsoft Research AI4Science, Beijing, China\
Peking University, Beijing, China and 3 Microsoft Research, Redmond, WA, USA\


Renqian Luo, Microsoft Research AI4Science: renqianluo@microsoft.com; \
Yingce Xia, Microsoft Research AI4Science: yinxia@microsoft.com; \
Tao Qin, Microsoft Research AI4Science, E-mail: taoqin@microsoft.com\

### Paper
BioGPT: Generative Pre-trained Transformer for Biomedical Text Generation and Mining\
https://arxiv.org/pdf/2210.10341.pdf


In [ ]:
####################################
# pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
################################

In [3]:
from transformers import pipeline, set_seed
from transformers import BioGptTokenizer, BioGptForCausalLM, AutoConfig
import torch

model = BioGptForCausalLM.from_pretrained("microsoft/biogpt")
tokenizer = BioGptTokenizer.from_pretrained("microsoft/biogpt")
generator = pipeline('text-generation', model=model, tokenizer=tokenizer)


In [1]:
from transformers import pipeline, set_seed
from transformers import GPT2LMHeadModel, GPT2Tokenizer, AutoTokenizer, AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained("/Users/beto/Documents/Projects/llama.cpp/models/MedGPT")
tokenizer = AutoTokenizer.from_pretrained("/Users/beto/Documents/Projects/llama.cpp/models/MedGPT")
generator = pipeline('text-generation', model=model, tokenizer=tokenizer)

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /Users/beto/Documents/Projects/llama.cpp/models/MedGPT and are newly initialized: ['model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.39.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.36.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.34.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'mode

# Text generator

In [2]:
set_seed(42)
QRY = "COVID-19 is"
#QRY = "What could be the diagnosis for a black person aged 43 with bmi 30 smoker low wbc count and high platelet count with flu-like symptoms and a body temperature of 38 degree Celsius"
generator(QRY, max_length=20, num_return_sequences=5, do_sample=True)

KeyboardInterrupt: 

# Tokenizer

In [6]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[ -9.5236,  -9.8918,  10.4556,  ...,  -9.3432,  -9.5866,  -9.0714],
         [ -5.0381,  -6.8491,   1.4589,  ...,  -7.0462,  -5.1944,  -6.3526],
         [-10.2718,  -9.9191,   3.5490,  ..., -10.1174, -10.5617,  -9.8093],
         ...,
         [-10.4497,  -9.3922,   5.5007,  ..., -11.6780, -11.1553,  -9.5711],
         [ -9.5377,  -9.0676,   5.7029,  ..., -10.3118, -10.5534,  -9.2811],
         [ -5.7361,  -5.9600,  18.0110,  ...,  -5.2634,  -5.5954,  -5.7066]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=((tensor([[[[ 0.9117,  0.9228,  2.4045,  ...,  0.3137, -0.0278, -0.7993],
          [-0.4103,  0.4885,  0.7616,  ...,  0.1325, -1.2912,  0.8270],
          [ 2.6415, -1.8419, -0.4256,  ..., -0.6972,  2.0653,  0.6028],
          ...,
          [-0.5474, -0.5226, -0.4017,  ...,  0.6868,  0.8941,  0.3468],
          [-0.1710, -0.1383, -0.7217,  ..., -1.0793,  0.8037, -1.0578],
          [-0.7257, -0.4265,  0.8490, 

In [8]:
tokenizer = BioGptTokenizer.from_pretrained("microsoft/biogpt")
model = BioGptForCausalLM.from_pretrained("microsoft/biogpt")

sentence = "COVID-19 is"
inputs = tokenizer(sentence, return_tensors="pt")

set_seed(42)

with torch.no_grad():
    beam_output = model.generate(**inputs,
                                min_length=100,
                                max_length=1024,
                                num_beams=5,
                                early_stopping=True
                                )
tokenizer.decode(beam_output[0], skip_special_tokens=True)

'COVID-19 is a global pandemic caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), the causative agent of coronavirus disease 2019 (COVID-19), which has spread to more than 200 countries and territories, including the United States (US), Canada, Australia, New Zealand, the United Kingdom (UK), and the United States of America (USA), as of March 11, 2020, with more than 800,000 confirmed cases and more than 800,000 deaths.'

In [9]:
from transformers import AutoTokenizer, BioGptModel


tokenizer = AutoTokenizer.from_pretrained("microsoft/biogpt")
model = BioGptModel.from_pretrained("microsoft/biogpt")

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state

Some weights of the model checkpoint at microsoft/biogpt were not used when initializing BioGptModel: ['output_projection.weight']
- This IS expected if you are initializing BioGptModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BioGptModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [10]:
last_hidden_states

tensor([[[-0.1223,  0.0990, -0.9851,  ..., -0.8175,  0.1483, -0.5747],
         [ 0.9615,  2.5404,  2.5730,  ...,  0.0366,  1.5262, -0.2498],
         [-0.8108,  2.0908,  2.5845,  ..., -1.3964,  2.7713, -0.5947],
         ...,
         [-0.5382, -0.4062,  0.5220,  ..., -0.7027, -0.4170,  1.0066],
         [ 2.0445, -0.6878,  1.0845,  ..., -0.2588, -1.0186,  1.9362],
         [-0.9987,  0.6902,  0.7713,  ..., -1.5325, -0.7416,  0.9632]]],
       grad_fn=<NativeLayerNormBackward0>)

# tocken classification

In [11]:
from transformers import AutoTokenizer, BioGptForTokenClassification
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/biogpt")
model = BioGptForTokenClassification.from_pretrained("microsoft/biogpt")

inputs = tokenizer(
    "HuggingFace is a company based in Paris and New York", add_special_tokens=False, return_tensors="pt"
)

with torch.no_grad():
    logits = model(**inputs).logits

predicted_token_class_ids = logits.argmax(-1)

# Note that tokens are classified rather then input words which means that
# there might be more predicted token classes than words.
# Multiple token classes might account for the same word
predicted_tokens_classes = [model.config.id2label[t.item()] for t in predicted_token_class_ids[0]]

labels = predicted_token_class_ids
loss = model(**inputs, labels=labels).loss

Some weights of the model checkpoint at microsoft/biogpt were not used when initializing BioGptForTokenClassification: ['output_projection.weight']
- This IS expected if you are initializing BioGptForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BioGptForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BioGptForTokenClassification were not initialized from the model checkpoint at microsoft/biogpt and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [12]:
labels

tensor([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

In [13]:
loss

tensor(0.4232, grad_fn=<NllLossBackward0>)

# Multilabel classification

In [18]:
import torch
from transformers import AutoTokenizer, BioGptForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("microsoft/biogpt")
model = BioGptForSequenceClassification.from_pretrained("microsoft/biogpt", problem_type="multi_label_classification")

inputs = tokenizer("Hi, i have been trying to do something interesting, but i cant, since im stupid", return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_ids = torch.arange(0, logits.shape[-1])[torch.sigmoid(logits).squeeze(dim=0) > 0.5]

# To train a model on `num_labels` classes, you can pass `num_labels=num_labels` to `.from_pretrained(...)`
num_labels = len(model.config.id2label)
model = BioGptForSequenceClassification.from_pretrained(
    "microsoft/biogpt", num_labels=num_labels, problem_type="multi_label_classification"
)

labels = torch.sum(
    torch.nn.functional.one_hot(predicted_class_ids[None, :].clone(), num_classes=num_labels), dim=1
).to(torch.float)
loss = model(**inputs, labels=labels).loss

Some weights of the model checkpoint at microsoft/biogpt were not used when initializing BioGptForSequenceClassification: ['output_projection.weight']
- This IS expected if you are initializing BioGptForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BioGptForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BioGptForSequenceClassification were not initialized from the model checkpoint at microsoft/biogpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of the model checkpoint at microsoft/biogpt were not used when initia

In [19]:
labels

tensor([[1., 1.]])

In [20]:
loss

tensor(0.5175, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [21]:
predicted_class_ids

tensor([0, 1])

In [30]:
from transformers import AutoTokenizer, AutoModelForCausalLM

# Load the BioGPT model
model_name = "microsoft/biogpt"
model = AutoModelForCausalLM.from_pretrained(model_name)

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Example question
question = "What is the role of DNA in genetics?"

# Tokenize the question
inputs = tokenizer(question, padding=True, truncation=True, return_tensors="pt")

# Generate response
outputs = model(**inputs)

# # Get the start and end indices of the answer
# start_index = torch.argmax(outputs.start_logits)
# end_index = torch.argmax(outputs.end_logits) + 1

# Decode the answer
answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(inputs["input_ids"][0]))

print("Answer:", answer)


Answer: </s>What is the role of DNA in genetics?
